name: Generate Datas

on:
  # Execute every 12 hours
  schedule:
    - cron: "0 */12 * * *"

  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    name: Jobs to Update Datas
    runs-on: ubuntu-latest

    steps:
      # Step 1: Generate the Snake Animation
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@master
        with:
          github_user_name: parvinrao079
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Step 2: Push the Animation to GitHub Pages
      - name: Push Snake Animation to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
